### ISSUE TITLE
Questions about datasets and code

### ISSUE THREAD

**Issue by fskong** [bxshi/ConMask#4]
Hi, thanks for your code. When I read your code, I run into some troubles.
1. How you get train.tails.idx? The length of train.tails.idx is not equal to train.txt. So as train.heads.idx.
2. How you get vocab.txt? I find not all words in descriptions exsists in vocab.txt.
3. I run the code on 8G*2 GPUs, OOM(out of memories) in No.1 global step.
   On 16G*4 GPUs, OOM(out of memories) in No.4848 step.
   I use 
  python3 -m ndkgc.models.fcn_model_v2 checkpoint_result data/dbpedia50 --force_eval --layer 3 --conv 2 --lr 1e-2 --keep_prob 0.5 --max_content 512 --pos 1 --neg 4 --open --neval 5000 --filter
Look forward to your reply.

**Comment by bxshi** [comment]
Hi, I need to check on 1. For 2, I believe it is from GloVe. As for 3, could you try `--max_content 256` and see if it works?

**Comment by fskong** [comment]
--max_content 256 doesn't have OOM until global_step 300. I think it works.
Thank you!

**Comment by bxshi** [comment]
Yeah, most likely this is because the CNN input is too large (batch_size *
max_content * embed_size ...). If it is possible, you can also reduce the
batch size in exchange for larger content size.

**Comment by fskong** [comment]
For 1, I ignore the 1 to n relations, and make a mistake. I think you don't need to check again.
