### ISSUE TITLE
How to reduce gpu to one?

### ISSUE THREAD

**Issue by chenhch8** [bxshi/ConMask#5]
Hello, thanks for your code very mush!
I recently use your code to train DKRL model, but it needs 4 GPUs, which my machine just have one. And from Readme I know it can reduce the gpus to one, but I don't konw how to change it. Would you mind to tell me briefly how to change the code?

**Comment by bxshi** [comment]
Try change https://github.com/bxshi/ConMask/blob/master/ndkgc/models/fcn_model_v2.py#L584 to one GPU and see if it works. 

If you encounter any memory error, please consider reducing the batch size and the max content length.

**Comment by bxshi** [comment]
And for DKRL, change `range(4)` to `range(1)` https://github.com/bxshi/ConMask/blob/master/ndkgc/models/dkrl.py#L496
