### ISSUE TITLE
libsampling.so ??? No such file or directory

### ISSUE THREAD

**Issue by LLLLLLoki** [bxshi/ConMask#7]
tensorflow.python.framework.errors_impl.NotFoundError: /home/ftlxj/XiaojunLiu/ConMask/ConMask/ndkgc/ops/./__sampling/libsampling.so: cannot open shared object file: No such file or directory

**Comment by bxshi** [comment]
Hi, I think you may need to compile that operator first.

**Comment by LLLLLLoki** [comment]
I am a novice, what is the role of cmake . 
                                                     cmake --build . and pairwise_sampler

**Comment by bxshi** [comment]
You can view cmake as a build tool, and  as for pairwisesampler, it is the
tnesorflow C++ operator.

**Comment by LLLLLLoki** [comment]
thank you
