### ISSUE TITLE
Error when I run the codes

### ISSUE THREAD

**Issue by xiangwf** [bxshi/ConMask#8]
after I run the cmakeList to generate the file,libsampling.so,I try to run the  command you give in the site.But A error happened and I can't find a correct way to fix it,could you help me ?
### libsampling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
My running environment is :python 3.6.5; tensorlfow 1.9.0; gcc 5.5
I heve already tried countless ways on the web  ,Hope you can help me soon

**Comment by bxshi** [comment]
Hi, the operator was written a while ago  and is no longer compatible with
the latest TF... would you mind try it with TF1.3? Thanks!

**Comment by xiangwf** [comment]
I'm sorry that I try to use the tensorflow1.3.but the error still happens!

**Comment by xiangwf** [comment]
and this is my Error
[
![2018-10-26 20-04-50](https://user-images.githubusercontent.com/18586019/47565270-89623980-d95a-11e8-95c0-f296ff40bc99.png)
](url)

**Comment by xiangwf** [comment]
this is what happened when I generate the libsampling.so :  
the ![2018-10-26 20-12-58](https://user-images.githubusercontent.com/18586019/47565593-96335d00-d95b-11e8-8e99-43142e0e875b.png)
I'm sorry to trouble you again and again!

**Comment by bxshi** [comment]
No worries at all! Looks like that you compiled the operator without any problem. Would you mind paste the error here? I can not open the first screenshot somehow. Thanks!

**Comment by xiangwf** [comment]
sorry about that!I'm a littlt worried!Thanks for your patience![47565270-89623980-d95a-11e8-95c0-f296ff40bc99](https://user-images.githubusercontent.com/18586019/47598428-08dd2080-d9ce-11e8-8814-a3bdd72d8733.png)
**The Error is  undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE**

**Comment by bxshi** [comment]
Try change https://github.com/bxshi/ConMask/blob/master/ndkgc/ops/__sampling/CMakeLists.txt#L9 

to 

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -shared -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0")`

Thanks.

**Comment by xiangwf** [comment]
Thanks for your patience again! have already solved this problem perfectly with your help!

**Comment by bxshi** [comment]
Good to know, closing this.
